# docker compose up --build

# docker compose exec hbase-dev bash
# or
# docker exec -it hbase bash
version: "3.9"
services:

  hbase-dev:
    container_name: hbase
    image: hibuz/hbase-dev
    build: .
    ports:
      - 9870:9870
      - 8088:8088
      - 16010:16010
      - 19888:19888
    #command: yarn,historyserver
    volumes:
      - hbase-vol:/tmp
      #- ../../../hbase-example:/home/hadoop/hbase-example:rw

volumes:
  hbase-vol: {}
